/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package example


import com.mongodb.kotlin.client.coroutine.MongoClient
import kotlinx.coroutines.flow.first
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import org.bson.*
import org.bson.types.ObjectId


@Serializable
data class Dog(
    @Contextual
    @SerialName("_id")
    val id: ObjectId,
    val name: String,
    val favoriteToy: String,
)



suspend fun main() {
    val winston = Dog(ObjectId(), "Winston", "Ball")


    val collection = MongoClient.create().getDatabase("test").getCollection<Dog>("Pet")
    collection.insertOne(winston)

    collection.withDocumentClass<Document>().find().first().also { println(it) }
    collection.withDocumentClass<Dog>().find().first().also { println(it) }


}

